package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierOrderCopy1<M extends BaseSupplierOrderCopy1<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public void setSupplierTime(java.util.Date supplierTime) {
		set("supplier_time", supplierTime);
	}
	
	public java.util.Date getSupplierTime() {
		return get("supplier_time");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setRemainderNum(java.math.BigDecimal remainderNum) {
		set("remainder_num", remainderNum);
	}
	
	public java.math.BigDecimal getRemainderNum() {
		return get("remainder_num");
	}

	public void setTax(java.lang.String tax) {
		set("tax", tax);
	}
	
	public java.lang.String getTax() {
		return getStr("tax");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setPayablePrice(java.math.BigDecimal payablePrice) {
		set("payable_price", payablePrice);
	}
	
	public java.math.BigDecimal getPayablePrice() {
		return get("payable_price");
	}

	public void setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
	}
	
	public java.lang.String getTradeType() {
		return getStr("trade_type");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setLogisticsName(java.lang.String logisticsName) {
		set("logistics_name", logisticsName);
	}
	
	public java.lang.String getLogisticsName() {
		return getStr("logistics_name");
	}

	public void setLogisticsId(java.lang.Long logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public java.lang.Long getLogisticsId() {
		return getLong("logistics_id");
	}

	public void setSupplierId(java.lang.Long supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Long getSupplierId() {
		return getLong("supplier_id");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
	}
	
	public java.lang.String getSupplierName() {
		return getStr("supplier_name");
	}

	public void setSupplierMobile(java.lang.String supplierMobile) {
		set("supplier_mobile", supplierMobile);
	}
	
	public java.lang.String getSupplierMobile() {
		return getStr("supplier_mobile");
	}

	public void setSupplierStoreId(java.lang.Long supplierStoreId) {
		set("supplier_store_id", supplierStoreId);
	}
	
	public java.lang.Long getSupplierStoreId() {
		return getLong("supplier_store_id");
	}

	public void setSupplierStoreName(java.lang.String supplierStoreName) {
		set("supplier_store_name", supplierStoreName);
	}
	
	public java.lang.String getSupplierStoreName() {
		return getStr("supplier_store_name");
	}

	public void setInvoiceFiledId(java.lang.String invoiceFiledId) {
		set("invoice_filed_id", invoiceFiledId);
	}
	
	public java.lang.String getInvoiceFiledId() {
		return getStr("invoice_filed_id");
	}

	public void setPayName(java.lang.String payName) {
		set("pay_name", payName);
	}
	
	public java.lang.String getPayName() {
		return getStr("pay_name");
	}

	public void setSupplierStoreAddress(java.lang.String supplierStoreAddress) {
		set("supplier_store_address", supplierStoreAddress);
	}
	
	public java.lang.String getSupplierStoreAddress() {
		return getStr("supplier_store_address");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setAmountPayable(java.math.BigDecimal amountPayable) {
		set("amount_payable", amountPayable);
	}
	
	public java.math.BigDecimal getAmountPayable() {
		return get("amount_payable");
	}

	public void setSupplierDocker(java.lang.String supplierDocker) {
		set("supplier_docker", supplierDocker);
	}
	
	public java.lang.String getSupplierDocker() {
		return getStr("supplier_docker");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setBillCompany(java.lang.String billCompany) {
		set("bill_company", billCompany);
	}
	
	public java.lang.String getBillCompany() {
		return getStr("bill_company");
	}

	public void setBillNo(java.lang.String billNo) {
		set("bill_no", billNo);
	}
	
	public java.lang.String getBillNo() {
		return getStr("bill_no");
	}

	public void setBillTel(java.lang.String billTel) {
		set("bill_tel", billTel);
	}
	
	public java.lang.String getBillTel() {
		return getStr("bill_tel");
	}

	public void setBillBank(java.lang.String billBank) {
		set("bill_bank", billBank);
	}
	
	public java.lang.String getBillBank() {
		return getStr("bill_bank");
	}

	public void setBillAccount(java.lang.String billAccount) {
		set("bill_account", billAccount);
	}
	
	public java.lang.String getBillAccount() {
		return getStr("bill_account");
	}

	public void setBillRemark(java.lang.String billRemark) {
		set("bill_remark", billRemark);
	}
	
	public java.lang.String getBillRemark() {
		return getStr("bill_remark");
	}

	public void setBillLinkman(java.lang.String billLinkman) {
		set("bill_linkman", billLinkman);
	}
	
	public java.lang.String getBillLinkman() {
		return getStr("bill_linkman");
	}

	public void setBillAddress(java.lang.String billAddress) {
		set("bill_address", billAddress);
	}
	
	public java.lang.String getBillAddress() {
		return getStr("bill_address");
	}

	public void setAuditReason(java.lang.String auditReason) {
		set("audit_reason", auditReason);
	}
	
	public java.lang.String getAuditReason() {
		return getStr("audit_reason");
	}

	public void setSupplierQuoteId(java.lang.Long supplierQuoteId) {
		set("supplier_quote_id", supplierQuoteId);
	}
	
	public java.lang.Long getSupplierQuoteId() {
		return getLong("supplier_quote_id");
	}

	public void setInvoiceFileNum(java.lang.String invoiceFileNum) {
		set("invoice_file_num", invoiceFileNum);
	}
	
	public java.lang.String getInvoiceFileNum() {
		return getStr("invoice_file_num");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}
	
	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}
	
	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setAdviceState(java.lang.Integer adviceState) {
		set("advice_state", adviceState);
	}
	
	public java.lang.Integer getAdviceState() {
		return getInt("advice_state");
	}

	public void setAdvicePrice(java.math.BigDecimal advicePrice) {
		set("advice_price", advicePrice);
	}
	
	public java.math.BigDecimal getAdvicePrice() {
		return get("advice_price");
	}

	public void setAdviceTime(java.util.Date adviceTime) {
		set("advice_time", adviceTime);
	}
	
	public java.util.Date getAdviceTime() {
		return get("advice_time");
	}

	public void setInvoiceStoreNum(java.math.BigDecimal invoiceStoreNum) {
		set("invoice_store_num", invoiceStoreNum);
	}
	
	public java.math.BigDecimal getInvoiceStoreNum() {
		return get("invoice_store_num");
	}

}
