package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierQuote<M extends BaseSupplierQuote<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setNormalPrice(java.math.BigDecimal normalPrice) {
		set("normal_price", normalPrice);
	}
	
	public java.math.BigDecimal getNormalPrice() {
		return get("normal_price");
	}

	public void setTaxPrice(java.math.BigDecimal taxPrice) {
		set("tax_price", taxPrice);
	}
	
	public java.math.BigDecimal getTaxPrice() {
		return get("tax_price");
	}

	public void setMfr(java.lang.String mfr) {
		set("mfr", mfr);
	}
	
	public java.lang.String getMfr() {
		return getStr("mfr");
	}

	public void setDiff(java.lang.Integer diff) {
		set("diff", diff);
	}
	
	public java.lang.Integer getDiff() {
		return getInt("diff");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setReleaseTime(java.util.Date releaseTime) {
		set("release_time", releaseTime);
	}
	
	public java.util.Date getReleaseTime() {
		return get("release_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setSupplierId(java.lang.Long supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Long getSupplierId() {
		return getLong("supplier_id");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}
	
	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setSurcharge(java.math.BigDecimal surcharge) {
		set("surcharge", surcharge);
	}
	
	public java.math.BigDecimal getSurcharge() {
		return get("surcharge");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
	}
	
	public java.lang.String getTradeType() {
		return getStr("trade_type");
	}

	public void setDeliveryAddress(java.lang.String deliveryAddress) {
		set("delivery_address", deliveryAddress);
	}
	
	public java.lang.String getDeliveryAddress() {
		return getStr("delivery_address");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setPaymentTime(java.util.Date paymentTime) {
		set("payment_time", paymentTime);
	}
	
	public java.util.Date getPaymentTime() {
		return get("payment_time");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
