package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResaleRelation<M extends BaseResaleRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSaleOrderId(java.lang.Long saleOrderId) {
		set("sale_order_id", saleOrderId);
	}
	
	public java.lang.Long getSaleOrderId() {
		return getLong("sale_order_id");
	}

	public void setPreSaleId(java.lang.Long preSaleId) {
		set("pre_sale_id", preSaleId);
	}
	
	public java.lang.Long getPreSaleId() {
		return getLong("pre_sale_id");
	}

	public void setSupplierOrderId(java.lang.Long supplierOrderId) {
		set("supplier_order_id", supplierOrderId);
	}
	
	public java.lang.Long getSupplierOrderId() {
		return getLong("supplier_order_id");
	}

	public void setIncomingMoneyId(java.lang.Long incomingMoneyId) {
		set("incoming_money_id", incomingMoneyId);
	}
	
	public java.lang.Long getIncomingMoneyId() {
		return getLong("incoming_money_id");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRelatedOrderId(java.lang.Long relatedOrderId) {
		set("related_order_id", relatedOrderId);
	}
	
	public java.lang.Long getRelatedOrderId() {
		return getLong("related_order_id");
	}

	public void setRelatedPreorderId(java.lang.Long relatedPreorderId) {
		set("related_preorder_id", relatedPreorderId);
	}
	
	public java.lang.Long getRelatedPreorderId() {
		return getLong("related_preorder_id");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
