package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogisticsOrder<M extends BaseLogisticsOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSaleOrderId(java.lang.Long saleOrderId) {
		set("sale_order_id", saleOrderId);
	}
	
	public java.lang.Long getSaleOrderId() {
		return getLong("sale_order_id");
	}

	public void setSupplierOrderId(java.lang.Long supplierOrderId) {
		set("supplier_order_id", supplierOrderId);
	}
	
	public java.lang.Long getSupplierOrderId() {
		return getLong("supplier_order_id");
	}

	public void setRelatedOrderId(java.lang.Long relatedOrderId) {
		set("related_order_id", relatedOrderId);
	}
	
	public java.lang.Long getRelatedOrderId() {
		return getLong("related_order_id");
	}

	public void setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.String getOrderType() {
		return getStr("order_type");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setFromArea(java.lang.String fromArea) {
		set("from_area", fromArea);
	}
	
	public java.lang.String getFromArea() {
		return getStr("from_area");
	}

	public void setToArea(java.lang.String toArea) {
		set("to_area", toArea);
	}
	
	public java.lang.String getToArea() {
		return getStr("to_area");
	}

	public void setFromAddress(java.lang.String fromAddress) {
		set("from_address", fromAddress);
	}
	
	public java.lang.String getFromAddress() {
		return getStr("from_address");
	}

	public void setToAddress(java.lang.String toAddress) {
		set("to_address", toAddress);
	}
	
	public java.lang.String getToAddress() {
		return getStr("to_address");
	}

	public void setFromAreaLasted(java.lang.String fromAreaLasted) {
		set("from_area_lasted", fromAreaLasted);
	}
	
	public java.lang.String getFromAreaLasted() {
		return getStr("from_area_lasted");
	}

	public void setToAreaLasted(java.lang.String toAreaLasted) {
		set("to_area_lasted", toAreaLasted);
	}
	
	public java.lang.String getToAreaLasted() {
		return getStr("to_area_lasted");
	}

	public void setFromAddressLasted(java.lang.String fromAddressLasted) {
		set("from_address_lasted", fromAddressLasted);
	}
	
	public java.lang.String getFromAddressLasted() {
		return getStr("from_address_lasted");
	}

	public void setToAddressLasted(java.lang.String toAddressLasted) {
		set("to_address_lasted", toAddressLasted);
	}
	
	public java.lang.String getToAddressLasted() {
		return getStr("to_address_lasted");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}
	
	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setAdditional(java.math.BigDecimal additional) {
		set("additional", additional);
	}
	
	public java.math.BigDecimal getAdditional() {
		return get("additional");
	}

	public void setFreightLasted(java.math.BigDecimal freightLasted) {
		set("freight_lasted", freightLasted);
	}
	
	public java.math.BigDecimal getFreightLasted() {
		return get("freight_lasted");
	}

	public void setAdditionalLasted(java.math.BigDecimal additionalLasted) {
		set("additional_lasted", additionalLasted);
	}
	
	public java.math.BigDecimal getAdditionalLasted() {
		return get("additional_lasted");
	}

	public void setLogisticsId(java.lang.Long logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public java.lang.Long getLogisticsId() {
		return getLong("logistics_id");
	}

	public void setLogisticsName(java.lang.String logisticsName) {
		set("logistics_name", logisticsName);
	}
	
	public java.lang.String getLogisticsName() {
		return getStr("logistics_name");
	}

	public void setContractFileId(java.lang.String contractFileId) {
		set("contract_file_id", contractFileId);
	}
	
	public java.lang.String getContractFileId() {
		return getStr("contract_file_id");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setReleaseDate(java.lang.String releaseDate) {
		set("release_date", releaseDate);
	}
	
	public java.lang.String getReleaseDate() {
		return getStr("release_date");
	}

	public void setDriverId(java.lang.Long driverId) {
		set("driver_id", driverId);
	}
	
	public java.lang.Long getDriverId() {
		return getLong("driver_id");
	}

	public void setDriverName(java.lang.String driverName) {
		set("driver_name", driverName);
	}
	
	public java.lang.String getDriverName() {
		return getStr("driver_name");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

	public void setPsNum(java.lang.String psNum) {
		set("ps_num", psNum);
	}
	
	public java.lang.String getPsNum() {
		return getStr("ps_num");
	}

	public void setDepositFileId(java.lang.String depositFileId) {
		set("deposit_file_id", depositFileId);
	}
	
	public java.lang.String getDepositFileId() {
		return getStr("deposit_file_id");
	}

	public void setCarId(java.lang.Long carId) {
		set("car_id", carId);
	}
	
	public java.lang.Long getCarId() {
		return getLong("car_id");
	}

	public void setPlateNo(java.lang.String plateNo) {
		set("plate_no", plateNo);
	}
	
	public java.lang.String getPlateNo() {
		return getStr("plate_no");
	}

}
