package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerCategory<M extends BaseCustomerCategory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCustomerId(java.lang.Long customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Long getCustomerId() {
		return getLong("customer_id");
	}

	public void setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Long getCategoryId() {
		return getLong("category_id");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
