package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOilFutures<M extends BaseOilFutures<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}
	
	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public void setChanges(java.lang.String changes) {
		set("changes", changes);
	}
	
	public java.lang.String getChanges() {
		return getStr("changes");
	}

	public void setUpDownScale(java.lang.String upDownScale) {
		set("up_down_scale", upDownScale);
	}
	
	public java.lang.String getUpDownScale() {
		return getStr("up_down_scale");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
