package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIncomingMoney<M extends BaseIncomingMoney<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setVariety(java.lang.String variety) {
		set("variety", variety);
	}
	
	public java.lang.String getVariety() {
		return getStr("variety");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}
	
	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}
	
	public java.lang.String getBank() {
		return getStr("bank");
	}

	public void setIncomingTime(java.util.Date incomingTime) {
		set("incoming_time", incomingTime);
	}
	
	public java.util.Date getIncomingTime() {
		return get("incoming_time");
	}

	public void setOutAccount(java.lang.String outAccount) {
		set("out_account", outAccount);
	}
	
	public java.lang.String getOutAccount() {
		return getStr("out_account");
	}

	public void setInAccount(java.lang.String inAccount) {
		set("in_account", inAccount);
	}
	
	public java.lang.String getInAccount() {
		return getStr("in_account");
	}

	public void setCustomerId(java.lang.Long customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Long getCustomerId() {
		return getLong("customer_id");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerTel(java.lang.String customerTel) {
		set("customer_tel", customerTel);
	}
	
	public java.lang.String getCustomerTel() {
		return getStr("customer_tel");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
