package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRelatedOrderCopy<M extends BaseRelatedOrderCopy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSaleOrderId(java.lang.Long saleOrderId) {
		set("sale_order_id", saleOrderId);
	}
	
	public java.lang.Long getSaleOrderId() {
		return getLong("sale_order_id");
	}

	public void setSupplierOrderId(java.lang.Long supplierOrderId) {
		set("supplier_order_id", supplierOrderId);
	}
	
	public java.lang.Long getSupplierOrderId() {
		return getLong("supplier_order_id");
	}

	public void setRelatedNum(java.math.BigDecimal relatedNum) {
		set("related_num", relatedNum);
	}
	
	public java.math.BigDecimal getRelatedNum() {
		return get("related_num");
	}

	public void setLogisticsId(java.lang.Long logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public java.lang.Long getLogisticsId() {
		return getLong("logistics_id");
	}

	public void setLogisticsName(java.lang.String logisticsName) {
		set("logistics_name", logisticsName);
	}
	
	public java.lang.String getLogisticsName() {
		return getStr("logistics_name");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}
	
	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setSurcharge(java.math.BigDecimal surcharge) {
		set("surcharge", surcharge);
	}
	
	public java.math.BigDecimal getSurcharge() {
		return get("surcharge");
	}

	public void setDriverId(java.lang.Long driverId) {
		set("driver_id", driverId);
	}
	
	public java.lang.Long getDriverId() {
		return getLong("driver_id");
	}

	public void setPlateNo(java.lang.String plateNo) {
		set("plate_no", plateNo);
	}
	
	public java.lang.String getPlateNo() {
		return getStr("plate_no");
	}

	public void setDriverName(java.lang.String driverName) {
		set("driver_name", driverName);
	}
	
	public java.lang.String getDriverName() {
		return getStr("driver_name");
	}

	public void setDriverTel(java.lang.String driverTel) {
		set("driver_tel", driverTel);
	}
	
	public java.lang.String getDriverTel() {
		return getStr("driver_tel");
	}

	public void setCardNo(java.lang.String cardNo) {
		set("card_no", cardNo);
	}
	
	public java.lang.String getCardNo() {
		return getStr("card_no");
	}

	public void setInvoiceFileId(java.lang.String invoiceFileId) {
		set("invoice_file_id", invoiceFileId);
	}
	
	public java.lang.String getInvoiceFileId() {
		return getStr("invoice_file_id");
	}

	public void setDepositFileId(java.lang.String depositFileId) {
		set("deposit_file_id", depositFileId);
	}
	
	public java.lang.String getDepositFileId() {
		return getStr("deposit_file_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setInvoiceFileNum(java.lang.String invoiceFileNum) {
		set("invoice_file_num", invoiceFileNum);
	}
	
	public java.lang.String getInvoiceFileNum() {
		return getStr("invoice_file_num");
	}

	public void setDepositFileNum(java.lang.String depositFileNum) {
		set("deposit_file_num", depositFileNum);
	}
	
	public java.lang.String getDepositFileNum() {
		return getStr("deposit_file_num");
	}

	public void setLogisticsFileId(java.lang.String logisticsFileId) {
		set("logistics_file_id", logisticsFileId);
	}
	
	public java.lang.String getLogisticsFileId() {
		return getStr("logistics_file_id");
	}

	public void setLogisticsFileNum(java.lang.String logisticsFileNum) {
		set("logistics_file_num", logisticsFileNum);
	}
	
	public java.lang.String getLogisticsFileNum() {
		return getStr("logistics_file_num");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setFromArea(java.lang.String fromArea) {
		set("from_area", fromArea);
	}
	
	public java.lang.String getFromArea() {
		return getStr("from_area");
	}

	public void setToArea(java.lang.String toArea) {
		set("to_area", toArea);
	}
	
	public java.lang.String getToArea() {
		return getStr("to_area");
	}

	public void setFromAddress(java.lang.String fromAddress) {
		set("from_address", fromAddress);
	}
	
	public java.lang.String getFromAddress() {
		return getStr("from_address");
	}

	public void setToAddress(java.lang.String toAddress) {
		set("to_address", toAddress);
	}
	
	public java.lang.String getToAddress() {
		return getStr("to_address");
	}

	public void setFromAreaLasted(java.lang.String fromAreaLasted) {
		set("from_area_lasted", fromAreaLasted);
	}
	
	public java.lang.String getFromAreaLasted() {
		return getStr("from_area_lasted");
	}

	public void setToAreaLasted(java.lang.String toAreaLasted) {
		set("to_area_lasted", toAreaLasted);
	}
	
	public java.lang.String getToAreaLasted() {
		return getStr("to_area_lasted");
	}

	public void setFromAddressLasted(java.lang.String fromAddressLasted) {
		set("from_address_lasted", fromAddressLasted);
	}
	
	public java.lang.String getFromAddressLasted() {
		return getStr("from_address_lasted");
	}

	public void setToAddressLasted(java.lang.String toAddressLasted) {
		set("to_address_lasted", toAddressLasted);
	}
	
	public java.lang.String getToAddressLasted() {
		return getStr("to_address_lasted");
	}

	public void setFreightLasted(java.math.BigDecimal freightLasted) {
		set("freight_lasted", freightLasted);
	}
	
	public java.math.BigDecimal getFreightLasted() {
		return get("freight_lasted");
	}

	public void setAdditionalLasted(java.math.BigDecimal additionalLasted) {
		set("additional_lasted", additionalLasted);
	}
	
	public java.math.BigDecimal getAdditionalLasted() {
		return get("additional_lasted");
	}

	public void setPsNum(java.lang.String psNum) {
		set("ps_num", psNum);
	}
	
	public java.lang.String getPsNum() {
		return getStr("ps_num");
	}

}
