package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogisticsCar<M extends BaseLogisticsCar<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPlateNo(java.lang.String plateNo) {
		set("plate_no", plateNo);
	}
	
	public java.lang.String getPlateNo() {
		return getStr("plate_no");
	}

	public void setCartType(java.lang.String cartType) {
		set("cart_type", cartType);
	}
	
	public java.lang.String getCartType() {
		return getStr("cart_type");
	}

	public void setOwnerName(java.lang.String ownerName) {
		set("owner_name", ownerName);
	}
	
	public java.lang.String getOwnerName() {
		return getStr("owner_name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setUserCharacter(java.lang.String userCharacter) {
		set("user_character", userCharacter);
	}
	
	public java.lang.String getUserCharacter() {
		return getStr("user_character");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public void setVin(java.lang.String vin) {
		set("vin", vin);
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public void setLogisticsId(java.lang.Long logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public java.lang.Long getLogisticsId() {
		return getLong("logistics_id");
	}

	public void setEngineNo(java.lang.String engineNo) {
		set("engine_no", engineNo);
	}
	
	public java.lang.String getEngineNo() {
		return getStr("engine_no");
	}

	public void setRegisterDate(java.util.Date registerDate) {
		set("register_date", registerDate);
	}
	
	public java.util.Date getRegisterDate() {
		return get("register_date");
	}

	public void setIssueDate(java.util.Date issueDate) {
		set("issue_date", issueDate);
	}
	
	public java.util.Date getIssueDate() {
		return get("issue_date");
	}

	public void setFileId(java.lang.String fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.String getFileId() {
		return getStr("file_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setLength(java.lang.String length) {
		set("length", length);
	}
	
	public java.lang.String getLength() {
		return getStr("length");
	}

	public void setCarUse(java.lang.String carUse) {
		set("car_use", carUse);
	}
	
	public java.lang.String getCarUse() {
		return getStr("car_use");
	}

	public void setTonnage(java.lang.String tonnage) {
		set("tonnage", tonnage);
	}
	
	public java.lang.String getTonnage() {
		return getStr("tonnage");
	}

	public void setVolume(java.lang.String volume) {
		set("volume", volume);
	}
	
	public java.lang.String getVolume() {
		return getStr("volume");
	}

	public void setLoad(java.lang.String load) {
		set("load", load);
	}
	
	public java.lang.String getLoad() {
		return getStr("load");
	}

	public void setLicense(java.lang.String license) {
		set("license", license);
	}
	
	public java.lang.String getLicense() {
		return getStr("license");
	}

	public void setWidth(java.lang.Double width) {
		set("width", width);
	}
	
	public java.lang.Double getWidth() {
		return getDouble("width");
	}

	public void setHeight(java.lang.String height) {
		set("height", height);
	}
	
	public java.lang.String getHeight() {
		return getStr("height");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

	public void setDriverId(java.lang.Long driverId) {
		set("driver_id", driverId);
	}
	
	public java.lang.Long getDriverId() {
		return getLong("driver_id");
	}

}
