package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogisticsDriver<M extends BaseLogisticsDriver<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setPlateNo(java.lang.String plateNo) {
		set("plate_no", plateNo);
	}
	
	public java.lang.String getPlateNo() {
		return getStr("plate_no");
	}

	public void setCardNo(java.lang.String cardNo) {
		set("card_no", cardNo);
	}
	
	public java.lang.String getCardNo() {
		return getStr("card_no");
	}

	public void setLogisticsId(java.lang.Long logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	public java.lang.Long getLogisticsId() {
		return getLong("logistics_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setLicense(java.lang.String license) {
		set("license", license);
	}
	
	public java.lang.String getLicense() {
		return getStr("license");
	}

	public void setCardFront(java.lang.String cardFront) {
		set("card_front", cardFront);
	}
	
	public java.lang.String getCardFront() {
		return getStr("card_front");
	}

	public void setCardBack(java.lang.String cardBack) {
		set("card_back", cardBack);
	}
	
	public java.lang.String getCardBack() {
		return getStr("card_back");
	}

	public void setQualifications(java.lang.String qualifications) {
		set("qualifications", qualifications);
	}
	
	public java.lang.String getQualifications() {
		return getStr("qualifications");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

	public void setSpecialRemark(java.lang.String specialRemark) {
		set("special_remark", specialRemark);
	}
	
	public java.lang.String getSpecialRemark() {
		return getStr("special_remark");
	}

}
