package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFutures<M extends BaseFutures<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}

	public void setClosingPrice(java.lang.String closingPrice) {
		set("closing_price", closingPrice);
	}
	
	public java.lang.String getClosingPrice() {
		return getStr("closing_price");
	}

	public void setOpeningPrice(java.lang.String openingPrice) {
		set("opening_price", openingPrice);
	}
	
	public java.lang.String getOpeningPrice() {
		return getStr("opening_price");
	}

	public void setHeightPrice(java.lang.String heightPrice) {
		set("height_price", heightPrice);
	}
	
	public java.lang.String getHeightPrice() {
		return getStr("height_price");
	}

	public void setMinimumPrice(java.lang.String minimumPrice) {
		set("minimum_price", minimumPrice);
	}
	
	public java.lang.String getMinimumPrice() {
		return getStr("minimum_price");
	}

	public void setVolume(java.lang.String volume) {
		set("volume", volume);
	}
	
	public java.lang.String getVolume() {
		return getStr("volume");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
