package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setQuoteId(java.lang.Long quoteId) {
		set("quote_id", quoteId);
	}
	
	public java.lang.Long getQuoteId() {
		return getLong("quote_id");
	}

	public void setSalesmanId(java.lang.Long salesmanId) {
		set("salesman_id", salesmanId);
	}
	
	public java.lang.Long getSalesmanId() {
		return getLong("salesman_id");
	}

	public void setOwnerUserId(java.lang.Long ownerUserId) {
		set("owner_user_id", ownerUserId);
	}
	
	public java.lang.Long getOwnerUserId() {
		return getLong("owner_user_id");
	}

	public void setTaxPrice(java.math.BigDecimal taxPrice) {
		set("tax_price", taxPrice);
	}
	
	public java.math.BigDecimal getTaxPrice() {
		return get("tax_price");
	}

	public void setNormalPrice(java.math.BigDecimal normalPrice) {
		set("normal_price", normalPrice);
	}
	
	public java.math.BigDecimal getNormalPrice() {
		return get("normal_price");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
