package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSavename(java.lang.String savename) {
		set("savename", savename);
	}
	
	public java.lang.String getSavename() {
		return getStr("savename");
	}

	public void setSavepath(java.lang.String savepath) {
		set("savepath", savepath);
	}
	
	public java.lang.String getSavepath() {
		return getStr("savepath");
	}

	public void setExt(java.lang.String ext) {
		set("ext", ext);
	}
	
	public java.lang.String getExt() {
		return getStr("ext");
	}

	public void setMime(java.lang.String mime) {
		set("mime", mime);
	}
	
	public java.lang.String getMime() {
		return getStr("mime");
	}

	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}

	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}

	public void setSha1(java.lang.String sha1) {
		set("sha1", sha1);
	}
	
	public java.lang.String getSha1() {
		return getStr("sha1");
	}

	public void setLocation(java.lang.Integer location) {
		set("location", location);
	}
	
	public java.lang.Integer getLocation() {
		return getInt("location");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
