package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setAliasTitle(java.lang.String aliasTitle) {
		set("alias_title", aliasTitle);
	}
	
	public java.lang.String getAliasTitle() {
		return getStr("alias_title");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setClassifyId(java.lang.Long classifyId) {
		set("classify_id", classifyId);
	}
	
	public java.lang.Long getClassifyId() {
		return getLong("classify_id");
	}

	public void setSourceName(java.lang.String sourceName) {
		set("source_name", sourceName);
	}
	
	public java.lang.String getSourceName() {
		return getStr("source_name");
	}

	public void setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
	}
	
	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}
	
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setClassifyName(java.lang.String classifyName) {
		set("classify_name", classifyName);
	}
	
	public java.lang.String getClassifyName() {
		return getStr("classify_name");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
