package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuoteSelf<M extends BaseQuoteSelf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setQuoteId(java.lang.Long quoteId) {
		set("quote_id", quoteId);
	}
	
	public java.lang.Long getQuoteId() {
		return getLong("quote_id");
	}

	public void setNormalPrice(java.math.BigDecimal normalPrice) {
		set("normal_price", normalPrice);
	}
	
	public java.math.BigDecimal getNormalPrice() {
		return get("normal_price");
	}

	public void setTaxPrice(java.math.BigDecimal taxPrice) {
		set("tax_price", taxPrice);
	}
	
	public java.math.BigDecimal getTaxPrice() {
		return get("tax_price");
	}

	public void setTax(java.lang.String tax) {
		set("tax", tax);
	}
	
	public java.lang.String getTax() {
		return getStr("tax");
	}

	public void setMfr(java.lang.String mfr) {
		set("mfr", mfr);
	}
	
	public java.lang.String getMfr() {
		return getStr("mfr");
	}

	public void setDiff(java.lang.Integer diff) {
		set("diff", diff);
	}
	
	public java.lang.Integer getDiff() {
		return getInt("diff");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setReleaseTime(java.util.Date releaseTime) {
		set("release_time", releaseTime);
	}
	
	public java.util.Date getReleaseTime() {
		return get("release_time");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setSalesmanId(java.lang.Long salesmanId) {
		set("salesman_id", salesmanId);
	}
	
	public java.lang.Long getSalesmanId() {
		return getLong("salesman_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
