package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}
	
	public java.lang.Long getPid() {
		return getLong("pid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setMergerName(java.lang.String mergerName) {
		set("merger_name", mergerName);
	}
	
	public java.lang.String getMergerName() {
		return getStr("merger_name");
	}

	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public void setMergerShortName(java.lang.String mergerShortName) {
		set("merger_short_name", mergerShortName);
	}
	
	public java.lang.String getMergerShortName() {
		return getStr("merger_short_name");
	}

	public void setLevelType(java.lang.Integer levelType) {
		set("level_type", levelType);
	}
	
	public java.lang.Integer getLevelType() {
		return getInt("level_type");
	}

	public void setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
	}
	
	public java.lang.String getCityCode() {
		return getStr("city_code");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}
	
	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

	public void setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
	}
	
	public java.lang.String getPinyin() {
		return getStr("pinyin");
	}

	public void setJianpin(java.lang.String jianpin) {
		set("jianpin", jianpin);
	}
	
	public java.lang.String getJianpin() {
		return getStr("jianpin");
	}

	public void setFirstChar(java.lang.String firstChar) {
		set("first_char", firstChar);
	}
	
	public java.lang.String getFirstChar() {
		return getStr("first_char");
	}

	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}
	
	public java.lang.String getLng() {
		return getStr("lng");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
