package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setSnsId(java.lang.String snsId) {
		set("sns_id", snsId);
	}
	
	public java.lang.String getSnsId() {
		return getStr("sns_id");
	}

	public void setSysThreadId(java.lang.String sysThreadId) {
		set("sys_thread_id", sysThreadId);
	}
	
	public java.lang.String getSysThreadId() {
		return getStr("sys_thread_id");
	}

	public void setSysAddress(java.lang.String sysAddress) {
		set("sys_address", sysAddress);
	}
	
	public java.lang.String getSysAddress() {
		return getStr("sys_address");
	}

	public void setSysPerson(java.lang.String sysPerson) {
		set("sys_person", sysPerson);
	}
	
	public java.lang.String getSysPerson() {
		return getStr("sys_person");
	}

	public void setSysDate(java.util.Date sysDate) {
		set("sys_date", sysDate);
	}
	
	public java.util.Date getSysDate() {
		return get("sys_date");
	}

	public void setSysProtocol(java.lang.String sysProtocol) {
		set("sys_protocol", sysProtocol);
	}
	
	public java.lang.String getSysProtocol() {
		return getStr("sys_protocol");
	}

	public void setSysRead(java.lang.String sysRead) {
		set("sys_read", sysRead);
	}
	
	public java.lang.String getSysRead() {
		return getStr("sys_read");
	}

	public void setSysStatus(java.lang.String sysStatus) {
		set("sys_status", sysStatus);
	}
	
	public java.lang.String getSysStatus() {
		return getStr("sys_status");
	}

	public void setSysType(java.lang.String sysType) {
		set("sys_type", sysType);
	}
	
	public java.lang.String getSysType() {
		return getStr("sys_type");
	}

	public void setSysReplyPathPresent(java.lang.String sysReplyPathPresent) {
		set("sys_reply_path_present", sysReplyPathPresent);
	}
	
	public java.lang.String getSysReplyPathPresent() {
		return getStr("sys_reply_path_present");
	}

	public void setSysSubject(java.lang.String sysSubject) {
		set("sys_subject", sysSubject);
	}
	
	public java.lang.String getSysSubject() {
		return getStr("sys_subject");
	}

	public void setSysBody(java.lang.String sysBody) {
		set("sys_body", sysBody);
	}
	
	public java.lang.String getSysBody() {
		return getStr("sys_body");
	}

	public void setSysServiceCenter(java.lang.String sysServiceCenter) {
		set("sys_service_center", sysServiceCenter);
	}
	
	public java.lang.String getSysServiceCenter() {
		return getStr("sys_service_center");
	}

	public void setTid(java.lang.Long tid) {
		set("tid", tid);
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

}
