package com.jinsubao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContractCopyCopy1<M extends BaseContractCopyCopy1<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setTax(java.lang.String tax) {
		set("tax", tax);
	}
	
	public java.lang.String getTax() {
		return getStr("tax");
	}

	public void setFileId(java.lang.String fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.String getFileId() {
		return getStr("file_id");
	}

	public void setPartaFileId(java.lang.String partaFileId) {
		set("parta_file_id", partaFileId);
	}
	
	public java.lang.String getPartaFileId() {
		return getStr("parta_file_id");
	}

	public void setPartbFileId(java.lang.String partbFileId) {
		set("partb_file_id", partbFileId);
	}
	
	public java.lang.String getPartbFileId() {
		return getStr("partb_file_id");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	public java.lang.String getNo() {
		return getStr("no");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUseCharacter(java.lang.String useCharacter) {
		set("use_character", useCharacter);
	}
	
	public java.lang.String getUseCharacter() {
		return getStr("use_character");
	}

}
