package com.jinsubao.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cms_article", "id", Article.class);
		arp.addMapping("cms_classify", "id", Classify.class);
		arp.addMapping("cms_quotation", "id", Quotation.class);
		arp.addMapping("cms_sms", "id", Sms.class);
		arp.addMapping("cst_cart", "id", Cart.class);
		arp.addMapping("cst_category", "id", Category.class);
		arp.addMapping("cst_contract", "id", Contract.class);
		arp.addMapping("cst_customer", "id", Customer.class);
		arp.addMapping("cst_customer_category", "id", CustomerCategory.class);
		arp.addMapping("cst_customer_demand", "id", CustomerDemand.class);
		arp.addMapping("cst_incoming_money", "id", IncomingMoney.class);
		arp.addMapping("cst_linkman", "id", Linkman.class);
		arp.addMapping("cst_logistics", "id", Logistics.class);
		arp.addMapping("cst_logistics_car", "id", LogisticsCar.class);
		arp.addMapping("cst_logistics_driver", "id", LogisticsDriver.class);
		arp.addMapping("cst_logistics_order", "id", LogisticsOrder.class);
		arp.addMapping("cst_message", "id", Message.class);
		arp.addMapping("cst_phycont", "id", Phycont.class);
		arp.addMapping("cst_presale_order", "id", PresaleOrder.class);
		arp.addMapping("cst_product", "id", Product.class);
		arp.addMapping("cst_quote", "id", Quote.class);
		arp.addMapping("cst_quote_extra", "id", QuoteExtra.class);
		arp.addMapping("cst_quote_self", "id", QuoteSelf.class);
		arp.addMapping("cst_related_order", "id", RelatedOrder.class);
		arp.addMapping("cst_related_preorder", "id", RelatedPreorder.class);
		arp.addMapping("cst_resale_relation", "id", ResaleRelation.class);
		arp.addMapping("cst_sale_order", "id", SaleOrder.class);
		arp.addMapping("cst_salesman", "id", Salesman.class);
		arp.addMapping("cst_supplier", "id", Supplier.class);
		arp.addMapping("cst_supplier_category", "id", SupplierCategory.class);
		arp.addMapping("cst_supplier_order", "id", SupplierOrder.class);
		arp.addMapping("cst_supplier_quote", "id", SupplierQuote.class);
		arp.addMapping("cst_supplier_store", "id", SupplierStore.class);
		arp.addMapping("cst_trader", "id", Trader.class);
		arp.addMapping("cst_voucher", "id", Voucher.class);
		arp.addMapping("fin_finance_customer", "id", FinFinanceCustomer.class);
		arp.addMapping("sys_area", "id", Area.class);
		arp.addMapping("sys_config", "id", Config.class);
		arp.addMapping("sys_data", "id", Data.class);
		arp.addMapping("sys_file", "id", File.class);
		arp.addMapping("sys_res", "id", Res.class);
		arp.addMapping("sys_user", "id", User.class);
	}
}

