package com.jinsubao.model;

import com.jinsubao.model.base.BaseContractCopyCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractCopyCopy1 extends BaseContractCopyCopy1<ContractCopyCopy1> {
	
}
