package com.jinsubao.model;

import com.jinsubao.model.base.BaseCustomerCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerCategory extends BaseCustomerCategory<CustomerCategory> {
	
}
