package com.jinsubao.model;

import com.jinsubao.model.base.BaseCustomerDemand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerDemand extends BaseCustomerDemand<CustomerDemand> {
	
}
