package com.jinsubao.model;

import com.jinsubao.model.base.BaseExchangeRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExchangeRate extends BaseExchangeRate<ExchangeRate> {
	
}
