package com.jinsubao.model;

import com.jinsubao.model.base.BaseFinFinanceCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinFinanceCustomer extends BaseFinFinanceCustomer<FinFinanceCustomer> {
	
}
