package com.jinsubao.model;

import com.jinsubao.model.base.BaseIncomingMoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IncomingMoney extends BaseIncomingMoney<IncomingMoney> {
	
}
