package com.jinsubao.model;

import com.jinsubao.model.base.BaseLogisticsCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsCar extends BaseLogisticsCar<LogisticsCar> {
	
}
