package com.jinsubao.model;

import com.jinsubao.model.base.BaseLogisticsOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsOrder extends BaseLogisticsOrder<LogisticsOrder> {
	
}
