package com.jinsubao.model;

import com.jinsubao.model.base.BaseLogisticsDriver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsDriver extends BaseLogisticsDriver<LogisticsDriver> {
	
}
