package com.jinsubao.model;

import com.jinsubao.model.base.BaseOilFutures;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OilFutures extends BaseOilFutures<OilFutures> {
	
}
