package com.jinsubao.model;

import com.jinsubao.model.base.BasePhycontCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhycontCopy extends BasePhycontCopy<PhycontCopy> {
	
}
