package com.jinsubao.model;

import com.jinsubao.model.base.BasePresaleOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PresaleOrder extends BasePresaleOrder<PresaleOrder> {
	
}
