package com.jinsubao.model;

import com.jinsubao.model.base.BasePresaleOrderCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PresaleOrderCopy extends BasePresaleOrderCopy<PresaleOrderCopy> {
	
}
