package com.jinsubao.model;

import com.jinsubao.model.base.BaseQuoteExtra;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuoteExtra extends BaseQuoteExtra<QuoteExtra> {
	
}
