package com.jinsubao.model;

import com.jinsubao.model.base.BaseRelatedOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelatedOrder extends BaseRelatedOrder<RelatedOrder> {
	
}
