package com.jinsubao.model;

import com.jinsubao.model.base.BaseRelatedPreorderCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelatedPreorderCopy extends BaseRelatedPreorderCopy<RelatedPreorderCopy> {
	
}
