package com.jinsubao.model;

import com.jinsubao.model.base.BaseRelatedOrderCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelatedOrderCopy extends BaseRelatedOrderCopy<RelatedOrderCopy> {
	
}
