package com.jinsubao.model;

import com.jinsubao.model.base.BaseRelatedPreorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelatedPreorder extends BaseRelatedPreorder<RelatedPreorder> {
	
}
