package com.jinsubao.model;

import com.jinsubao.model.base.BaseResaleRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResaleRelation extends BaseResaleRelation<ResaleRelation> {
	
}
