package com.jinsubao.model;

import com.jinsubao.model.base.BaseSaleOrderCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleOrderCopy extends BaseSaleOrderCopy<SaleOrderCopy> {
	
}
