package com.jinsubao.model;

import com.jinsubao.model.base.BaseSpotMarket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpotMarket extends BaseSpotMarket<SpotMarket> {
	
}
