package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierOrderCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierOrderCopy1 extends BaseSupplierOrderCopy1<SupplierOrderCopy1> {
	
}
