package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierCopy extends BaseSupplierCopy<SupplierCopy> {
	
}
