package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierCopy1 extends BaseSupplierCopy1<SupplierCopy1> {
	
}
