package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierCategory extends BaseSupplierCategory<SupplierCategory> {
	
}
