package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierCopy2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierCopy2 extends BaseSupplierCopy2<SupplierCopy2> {
	
}
