package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierStore extends BaseSupplierStore<SupplierStore> {
	
}
