package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierOrderCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierOrderCopy extends BaseSupplierOrderCopy<SupplierOrderCopy> {
	
}
