package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierOrder extends BaseSupplierOrder<SupplierOrder> {
	
}
