package com.jinsubao.model;

import com.jinsubao.model.base.BaseSupplierQuote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierQuote extends BaseSupplierQuote<SupplierQuote> {
	
}
