package com.jinsubao.model;

import com.jinsubao.model.base.BaseVoucherCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VoucherCopy extends BaseVoucherCopy<VoucherCopy> {
	
}
